import { readdir, readFile } from "fs/promises";
import path from "path";
import { PATHS } from "@/config/paths-config";

const VAULT_PATH = PATHS.obsidianVault;

const SESSION_DIRS = [
  { dir: path.join(VAULT_PATH, "CycloneOS", "sessions"), source: "cycloneos" },
  {
    dir: path.join(VAULT_PATH, "Draco", "01.OpenClaw", "Claude session-logs"),
    source: "general",
  },
];

export interface SessionEntry {
  name: string;
  date: string;
  session: number;
  source: string;
  sessionType?: string;
  summary?: string;
  path: string;
}

/**
 * Parse session number from filename like "2026-03-24-session-27.md"
 */
function parseSessionFilename(
  filename: string
): { date: string; session: number } | null {
  const match = filename.match(/^(\d{4}-\d{2}-\d{2})-session-(\d+)\.md$/);
  if (!match) return null;
  return { date: match[1], session: parseInt(match[2], 10) };
}

/**
 * Extract summary from session log frontmatter/content.
 * Looks for the first "## 目標" or "## 本次 Session 目標" section.
 */
function extractSummary(content: string): string | undefined {
  // Try to find 目標 section
  const goalMatch = content.match(
    /##\s*(?:目標|本次 Session 目標)\s*\n([\s\S]*?)(?:\n##|\n---|\Z)/
  );
  if (goalMatch) {
    const lines = goalMatch[1]
      .trim()
      .split("\n")
      .filter((l) => l.trim().startsWith("- "))
      .map((l) => l.trim().replace(/^-\s*/, ""))
      .slice(0, 2);
    if (lines.length > 0) return lines.join("；");
  }

  // Fallback: try 摘要 section
  const summaryMatch = content.match(
    /##\s*摘要\s*\n([\s\S]*?)(?:\n##|\n---|\Z)/
  );
  if (summaryMatch) {
    return summaryMatch[1].trim().split("\n")[0].replace(/^-\s*/, "");
  }

  return undefined;
}

/**
 * Extract session-type from frontmatter
 */
function extractSessionType(content: string): string | undefined {
  const match = content.match(/^session-type:\s*(.+)$/m);
  return match ? match[1].trim() : undefined;
}

/**
 * Check if a session log was auto-generated by a hook (low-value).
 * Only checks frontmatter tags — not full content, to avoid false positives
 * when a real session log merely *mentions* "auto-generated".
 */
function isAutoGenerated(content: string): boolean {
  // Extract frontmatter (between --- delimiters)
  const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
  if (!fmMatch) return false;
  const frontmatter = fmMatch[1];

  // Check if tags contain "auto-generated"
  const tagsMatch = frontmatter.match(/^tags:\s*\[([^\]]*)\]/m);
  if (tagsMatch) {
    const tags = tagsMatch[1].split(",").map((t) => t.trim());
    if (tags.includes("auto-generated")) return true;
  }

  // Also check for the hook marker in frontmatter only
  if (frontmatter.includes("SessionEnd hook 自動產生")) return true;

  return false;
}

/**
 * Scan session log directories and return recent sessions.
 */
export async function getRecentSessions(
  days: number = 7
): Promise<SessionEntry[]> {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - days);
  cutoff.setHours(0, 0, 0, 0);

  const results: SessionEntry[] = [];

  for (const { dir, source } of SESSION_DIRS) {
    let files: string[];
    try {
      files = await readdir(dir);
    } catch {
      continue;
    }

    for (const file of files) {
      const parsed = parseSessionFilename(file);
      if (!parsed) continue;

      const fileDate = new Date(parsed.date + "T00:00:00");
      if (fileDate < cutoff) continue;

      const filePath = path.join(dir, file);

      // Read head for summary extraction and filtering
      let summary: string | undefined;
      let sessionType: string | undefined;
      try {
        const content = await readFile(filePath, "utf-8");
        const head = content.slice(0, 1500);

        // Skip auto-generated hook logs (no meaningful content)
        if (isAutoGenerated(head)) continue;

        summary = extractSummary(head);
        sessionType = extractSessionType(head);
      } catch {
        // skip summary if unreadable
      }

      results.push({
        name: file,
        date: parsed.date,
        session: parsed.session,
        source,
        sessionType,
        summary,
        path: filePath,
      });
    }
  }

  // Sort newest first (by date desc, then session number desc)
  results.sort((a, b) => {
    const dateCmp = b.date.localeCompare(a.date);
    if (dateCmp !== 0) return dateCmp;
    return b.session - a.session;
  });

  return results;
}

/**
 * Return the count of today's sessions.
 */
export async function getTodaySessionCount(): Promise<number> {
  const today = new Date().toISOString().slice(0, 10);
  const sessions = await getRecentSessions(1);
  return sessions.filter((s) => s.date === today).length;
}
