// src/app/api/presentations/generate-image/route.ts

import { NextRequest } from "next/server";
import { feloLiveDoc } from "@/lib/felo/livedoc";
import { feloSuperAgent, extractImageUrls } from "@/lib/felo/superagent";
import { writeFile, mkdir } from "fs/promises";
import { join } from "path";
import { PATHS } from "@/config/paths-config";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function POST(req: NextRequest) {
  const { imagePrompt } = await req.json();

  if (!imagePrompt || typeof imagePrompt !== "string") {
    return Response.json({ error: "imagePrompt is required" }, { status: 400 });
  }

  try {
    const liveDoc = await feloLiveDoc.getOrCreate();

    const result = await feloSuperAgent({
      query: `Generate an image: ${imagePrompt}`,
      liveDocId: liveDoc.short_id,
      acceptLanguage: "en",
    });

    const imageUrls = extractImageUrls(result);
    if (imageUrls.length === 0) {
      return Response.json(
        { error: "No images generated by SuperAgent" },
        { status: 502 },
      );
    }

    const imageUrl = imageUrls[0];
    const timestamp = Date.now();
    const filename = `felo-img-${timestamp}.png`;

    await mkdir(PATHS.feloImages, { recursive: true });

    const imgRes = await fetch(imageUrl);
    if (!imgRes.ok) {
      return Response.json(
        { error: `Failed to download image: ${imgRes.status}` },
        { status: 502 },
      );
    }

    const imgBuffer = Buffer.from(await imgRes.arrayBuffer());
    const localFilePath = join(PATHS.feloImages, filename);
    await writeFile(localFilePath, imgBuffer);

    const localPath = `/uploads/felo/images/${filename}`;

    return Response.json({
      localPath,
      prompt: imagePrompt,
      createdAt: new Date().toISOString(),
      allImageUrls: imageUrls,
    });
  } catch (e) {
    console.error("[generate-image] error:", e);
    return Response.json(
      { error: e instanceof Error ? e.message : "Image generation failed" },
      { status: 500 },
    );
  }
}
